force-app/main/default/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <label>Loan Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <label>Loan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Charge Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LoanTriggerHandler.cls
public class LoanTriggerHandler {
    public static void handleAfterInsert(List<Loan__c> newLoans) {
        List<Loan_Charge__c> chargesToCreate = new List<Loan_Charge__c>();

        for (Loan__c loan : newLoans) {
            Date releaseDate = loan.Date_Loan_Issued__c.addMonths(Integer.valueOf(loan.Term__c));
            chargesToCreate.add(new Loan_Charge__c(
                Loan__c = loan.Id,
                Charge_Type__c = 'Release Charge',
                Amount__c = 500,
                Date__c = releaseDate
            ));
        }

        insert chargesToCreate;
    }

    public static void handleAfterUpdate(List<Loan__c> newLoans, Map<Id, Loan__c> oldMap) {
        List<Loan_Charge__c> chargesToCreate = new List<Loan_Charge__c>();
        List<Loan_Charge__c> chargesToUpdate = new List<Loan_Charge__c>();

        for (Loan__c loan : newLoans) {
            Loan__c oldLoan = oldMap.get(loan.Id);
            if (loan.Term__c != oldLoan.Term__c) {
                // 1. Update Release Charge date
                Date newReleaseDate = loan.Date_Loan_Issued__c.addMonths(Integer.valueOf(loan.Term__c));

                Loan_Charge__c releaseCharge = LoanService.getReleaseChargeForLoan(loan.Id);
                if (releaseCharge != null) {
                    releaseCharge.Date__c = newReleaseDate;
                    chargesToUpdate.add(releaseCharge);
                }

                // 2. Add Admin Fee
                chargesToCreate.add(new Loan_Charge__c(
                    Loan__c = loan.Id,
                    Charge_Type__c = 'Admin Fee',
                    Amount__c = 300,
                    Date__c = Date.today()
                ));
            }
        }

        if (!chargesToUpdate.isEmpty()) update chargesToUpdate;
        if (!chargesToCreate.isEmpty()) insert chargesToCreate;
    }
}